### PR TITLE
fix: React adapter behavior has now been fixed

### LINKED ISSUE #1901: form.setErrorMap is not a function
### Describe the bug

Getting `form.setErrorMap is not a function` after updating to `@tanstack/react-form@1.26.0`

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-form-nvmd8gjz?file=src%2Findex.tsx

### Steps to reproduce

Try to use `form.setErrorMap`, see line 33 in the link above

### Expected behavior

Read the changlogs for react-form and form-core, didn't see any mentioning of removal of that API. So I'd expect not seeing that error.

### How often does this bug happen?

Every time

### Screenshots or Videos

_No response_

### Platform

MacOS, Chrome

### TanStack Form adapter

None

### TanStack Form version

1.26.0

### TypeScript version

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by crutchcorn**
Closes #1901

### CODE REVIEW

File: packages/react-form/src/useForm.tsx [hunk 1]
```diff
@@ -226,6 +226,9 @@ export function useForm<
       TSubmitMeta
     > = {
       ...formApi,
+      handleSubmit: ((...props: never[]) => {
+        formApi._handleSubmit(...props)
```
Comment (vedovelli) [inline packages/react-form/src/useForm.tsx:230]: Version `1.27.1` introduced a regression in the `handleSubmit` wrapper that breaks promise handling.

In [PR #1903](https://github.com/TanStack/form/pull/1903), TanStack converted class methods to arrow functions to fix `setErrorMap` not being available after spreading. However, the `handleSubmit` wrapper in `useForm.tsx` is missing a `return` statement:

```typescript
// Current (broken)
handleSubmit: ((...props: never[]) => {
  formApi._handleSubmit(...props)  // Missing return!
}) as typeof formApi.handleSubmit,
```

This causes:
- `await form.handleSubmit()` resolves immediately instead of waiting for submission
- `onError` callbacks don't propagate correctly
- Error state not captured in hooks

Comment (crutchcorn) [reply packages/react-form/src/useForm.tsx:230]: Already fixed by: https://github.com/TanStack/form/pull/1924

Just needs to release (will do now)

Comment (vedovelli) [reply packages/react-form/src/useForm.tsx:230]: Thanks a lot!
