### PR TITLE
fix(form-core): handle string array indices in prefixSchemaToErrors

### LINKED ISSUE #1683: `prefixSchemaToErrors` does not support paths for arrays of objects
### Describe the bug

Given a form that represents an array of objects such as `{ people: [ { name: 'Alex' } ] }`, the `name` field name would be `people[0].name`.

When the form is validated with a library that supports Standard Schema, the validator will return something along the lines of:

```
{
  issues: {
    message: 'This field is required.',
    path: ['people', '0', 'name']
  }
}
```

However, when `prefixSchemaToErrors` processes that validation value, `prefixSchemaToErrors` returns the path `"people.0."name` and then uses that string to hold the validation message in `formApi.state.errors`. The field will not render the validation message because the key does not match the field name.

### Your minimal, reproducible example

https://stackblitz.com/edit/tanstack-form-zzmhzozz?file=src%2Findex.tsx

### Steps to reproduce

1. Go to https://stackblitz.com/edit/tanstack-form-zzmhzozz?file=src%2Findex.tsx
2. Note that there are no errors on the form
3. Click "Add Person"
4. Note that the form's validations are run on button click
5. Note that the `title` field has a field-specific validation message AND the validation message is present in the `state.errors` and `state.errorMap` values that are rendered at the bottom of the page.
6. Note that the `people[0].name` field _HAS NO_ field-specific validation message AND the validation message is present in the `state.errors` and `state.errorMap` values that are rendered at the bottom of the page. This is due to the error path not matching the field name due to how `prefixSchemaToErrors` reconstitutes the path.

### Expected behavior

`prefixSchemaToErrors` should return the path `"people[0].name"` to match the [implied naming standard in `@tanstack/form`.](https://tanstack.com/form/v1/docs/framework/react/guides/arrays)

### How often does this bug happen?

Every time

### Screenshots or Videos

Image

### Platform

Version 138.0.7204.185 (Official Build) (arm64)

### TanStack Form adapter

react-form

### TanStack Form version

1.15.1

### TypeScript version

_No response_

### Additional context

Additionally, I'd love to see something that indicates what the expected format is for non-trivial field names to make this clearer.

### PR DESCRIPTION
**Pull request by jiji-hoon96**
## Description

This PR fixes a bug in the `prefixSchemaToErrors` function within `standardSchemaValidator.ts` where array indices passed as strings (like '0', '1') were not being properly converted to bracket notation, causing validation errors for array fields to be incorrectly formatted.

### Problem
- Standard Schema validation libraries handle array indices differently:
  - **Zod**: passes numeric indices (0, 1, 2)
  - **Yup**: passes string indices ('0', '1', '2')
- The existing code only checked for `typeof normalizedSegment === 'number'`, missing string-based indices
- This caused paths like `people.0.name` instead of the correct `people[0].name`

### Solution
- Enhanced the array index detection logic to handle both numeric and string indices
- Added regex pattern `/^\d+$/` to identify string representations of numbers
- Maintained backward compatibility with existing numeric index handling
- Ensured TypeScript type safety throughout the changes

## Related Issue
Fixes #1683

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing
- [x] Added comprehensive test cases covering:
  - Numeric array indices (Zod compatibility)
  - String array indices (Yup compatibility) 
  - Nested arrays with mixed index types
  - Regular object paths without arrays
- [x] All existing tests continue to pass
- [x] New tests verify the fix works correctly

### Test Results
```bash
✓ standard schema validator > array path handling > should handle numeric array indices correctly
✓ standard schema validator > array path handling > should handle string array indices correctly (Yup compatibility)  
✓ standard schema validator > array path handling > should handle nested arrays with mixed numeric and string indices
✓ standard schema validator > array path handling > should handle regular object paths without array indices
```

### Before
```typescript
return typeof normalizedSegment === 'number'
  ? `[${normalizedSegment}]`
  : normalizedSegment
```

### After
```typescript
// Check if segment is a number or a string that represents a valid array index
const isArrayIndex = 
  typeof normalizedSegment === 'number' ||
  (typeof normalizedSegment === 'string' && /^\d+$/.test(normalizedSegment))

return isArrayIndex
  ? `[${normalizedSegment}]`
  : normalizedSegment
```

## Impact
- ✅ Fixes array field validation error display issues
- ✅ Maintains compatibility with all existing Standard Schema implementations
- ✅ No breaking changes to existing functionality
- ✅ Improves developer experience when using array validations

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: packages/form-core/src/standardSchemaValidator.ts [hunk 1]
```diff
@@ -27,9 +27,12 @@ function prefixSchemaToErrors(issues: readonly StandardSchemaV1Issue[]) {
...
-        return typeof normalizedSegment === 'number'
-          ? `[${normalizedSegment}]`
-          : normalizedSegment
+        const isArrayIndex =
+          typeof normalizedSegment === 'number' ||
+          (typeof normalizedSegment === 'string' &&
+            /^\d+$/.test(normalizedSegment))
+
+        return isArrayIndex ? `[${normalizedSegment}]` : normalizedSegment
       })
```
Comment (LeCarbonator) [inline packages/form-core/src/standardSchemaValidator.ts]: This breaks for numeric properties (example: `foo.01234.bar`). Ideally, we also need unit tests to ensure they don't break with this implementation.

However, the standard schema validator has access to the form value it validated, so we can use it as reference to see if the access is an array or not.

Something like this:
```tsx
function prefixSchemaToErrors(
  issues: readonly StandardSchemaV1Issue[],
  formValue: unknown,
) {
  const schema = new Map<string, StandardSchemaV1Issue[]>()

  for (const issue of issues) {
    const issuePath = issue.path ?? []

    let currentFormValue = formValue
    let path = ''

    for (let i = 0; i < issuePath.length; i++) {
      const pathSegment = issuePath[i]!
      const segment =
        typeof pathSegment === 'object' ? pathSegment.key : pathSegment

      // Standard Schema doesn't specify if paths should use numbers or stringified numbers for array access.
      // However, if we follow the path it provides and encounter an array, then we can assume it's intended for array access.
      const segmentAsNumber = Number(segment)
      if (Array.isArray(currentFormValue) && !isNaN(segmentAsNumber)) {
        path += `[${segmentAsNumber}]`
      } else {
        path += (i > 0 ? '.' : '') + String(segment)
      }

      if (
        typeof currentFormValue === 'object' &&
        currentFormValue !== null
      ) {
        currentFormValue = currentFormValue[segment as never]
      } else {
        currentFormValue = undefined
      }
    }
    schema.set(path, (schema.get(path) ?? []).concat(issue))
  }

  return Object.fromEntries(schema)
}
```

File: packages/form-core/tests/standardSchemaValidator.spec.ts [hunk 2]
```diff
@@ -398,4 +398,161 @@ describe('standard schema validator', () => {
...
+
+      field.setValue('')
+      expect(form.state.errors).toMatchObject([
+        {
+          'people[0].name': [{ message: 'Name is required' }],
+        },
+      ])
+    })
+
+    it('should handle string array indices correctly (Yup compatibility)', async () => {
```
Comment (LeCarbonator) [inline packages/form-core/tests/standardSchemaValidator.spec.ts]: Nitpick, but this is less about Yup being special, and more about standard schema not specifying what a path should contain. It could be any library implementing standard schema.

File: packages/form-core/tests/standardSchemaValidator.spec.ts [hunk 3]
```diff
@@ -398,4 +398,161 @@ describe('standard schema validator', () => {
...
+                    message: 'Name is required',
+                    path: ['people', '0', 'name'], // String index like Yup
+                  },
+                ],
+              }
+            }
+            return { value: typedValue }
+          },
+        },
+      }
```
Comment (LeCarbonator) [inline packages/form-core/tests/standardSchemaValidator.spec.ts]: There's no need to mock a validator. 

Zod allows you to set a custom path, allowing us to imitate string paths.

```tsx
z.object({ 
   people: z.array(z.object({ 
       name: z.string() 
   }))
}).superRefine((_, ctx) => {
    ctx.addIssue({
        code: 'custom',
        message: 'Name is required',
        path: [ 'people', '0', 'name' ],
    })
})
```

File: packages/form-core/tests/standardSchemaValidator.spec.ts [hunk 4]
```diff
@@ -398,4 +398,161 @@ describe('standard schema validator', () => {
...
+      field.mount()
+
+      field.setValue('')
+      expect(form.state.errors).toMatchObject([
+        {
+          'user.profile.name': [{ message: 'Name is required' }],
+        },
+      ])
+    })
+  })
```
Comment (LeCarbonator) [inline packages/form-core/tests/standardSchemaValidator.spec.ts:585]: Failing unit test for the numeric property comment above:
```tsx
  it('should allow numeric object properties for standard schema issue paths', () => {
    const form = new FormApi({
      defaultValues: {
        foo: {
          0: { bar: '' },
        },
      },
      validators: {
        onChange: z.object({
          foo: z.object({
            0: z.object({ bar: z.string().email('Must be an email') }),
          }),
        }),
      },
    })
    form.mount()

    const field = new FieldApi({
      form,
      name: 'foo.0.bar',
    })
    field.mount()

    field.setValue('test')

    expect(form.state.errors).toMatchObject([
      { 'foo.0.bar': [{ message: 'Must be an email' }] },
    ])
    expect(field.state.meta.errors).toMatchObject([
      { message: 'Must be an email' },
    ])
  })
```

**Comment by jiji-hoon96** [comment]
Thank you for the excellent feedback! Your suggestions were spot-on and made the implementation much more robust.

I really appreciate you pointing out the numeric object property issue and providing the better approach using actual form values as reference. The `Array.isArray(currentFormValue)` solution is much more reliable than my initial regex approach.

I've committed all the changes incorporating your feedback
- ✅ Form value reference instead of regex detection  
- ✅ Updated test descriptions and replaced mocks with Zod's `superRefine`
- ✅ Added the numeric property test case
- ✅ All tests passing

Please review when you have a chance. Thanks for the great mentorship!

**Comment by dlindahl** [comment]
Appreciate the work here, but something made me wonder... in the interest of openness, has this PR been created by AI by any chance?

**Comment by jiji-hoon96** [comment]
I wrote the bug fix logic myself. However, I did refer to some reference materials while searching for an efficient way to implement the code. Could this be a problem?

**Comment by dlindahl** [comment]
@jiji-hoon96 I am not making any claims on the work itself. I was asking just out of curiosity based on the PR itself. No worries! ✌️

**Comment by jiji-hoon96** [comment]
@LeCarbonator Three weeks have passed. If there are no issues, wouldn't it be okay to merge the work? 😀
